### ISSUE TITLE
Missing CameraReadout in CameraDescription

### ISSUE THREAD

**Issue by aleberti** [cta-observatory/ctapipe_io_magic#3]
In the passage to ctapipe v0.12 (see #1), CameraDescription has an attribute which is a CameraReadout object. This class is filled from a file fits.gz, which is read whenever the CameraDescription is created with the method from_name (e.g. CameraDescription.from_name("MAGICCam") gives the MAGIC camera description). This file is not produced for MAGIC (the CameraReadout is a new class), so we should produce it and upload it to the CTA server where all this kind of data is stored.

An example for such fits.gz file is the one for LSTCam.

See also https://github.com/cta-observatory/ctapipe/blob/v0.12.0/ctapipe/instrument/camera/readout.py.

To create the needed file, in principle one could do also:

```python
from ctapipe.instrument import CameraReadout
import numpy as np
import astropy.units as u
from astropy.table import Table

pulse_shape_lo_gain = np.array([...]) #fill with some pulse shape
pulse_shape_hi_gain = np.array([...]) #fill with some pulse shape
pulse_shape = np.vstack((pulse_shape_lo_gain, pulse_shape_lo_gain))
camera_readout = CameraReadout(
    camera_name='MAGICCam',
    sampling_rate=u.Quantity(1.64, u.GHz),
    reference_pulse_shape=pulse_shape,
    reference_pulse_sample_width=u.Quantity(0.5, u.ns)
)

camera_readout_table = camera_readout.to_table()
camera_readout_table.write("MAGICCam.camreadout.fits.gz")
```

**Comment by YoshikiOhtani** [comment]
Hi @aleberti, I'm not sure it is related to this, but suddenly I faced the following errors when importing ctapipe.io.hdf5tableio.HDF5TableWriter:

```
from ctapipe.io import HDF5TableWriter
Another process is already running, waiting: 319.4s^C---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/filelock.py in __enter__(self)
     21             try:
---> 22                 self.path.open("x").close()
     23                 break

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
   1207         return io.open(self, mode, buffering, encoding, errors, newline,
-> 1208                        opener=self._opener)
   1209 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/pathlib.py in _opener(self, name, flags, mode)
   1062         # A stub for the opener argument to built-in open()
-> 1063         return self._accessor.open(self, flags, mode)
   1064 

FileExistsError: [Errno 17] File exists: '/home/yoshiki.ohtani/.cache/ctapipe/cccta-dataserver.in2p3.fr/data/ctapipe-extra/v0.3.3/MAGICCam.camreadout.fits.gz.lock'

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-4-f0731f6ee983> in <module>
----> 1 from ctapipe.io import HDF5TableWriter

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/io/__init__.py in <module>
     15 
     16 # import IO plugins with their event sources
---> 17 detect_and_import_io_plugins()
     18 
     19 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py in detect_and_import_io_plugins()
     15 
     16 def detect_and_import_io_plugins():
---> 17     return detect_and_import_plugins(prefix="ctapipe_io_")

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py in detect_and_import_plugins(prefix)
      9     return {
     10         name: importlib.import_module(name)
---> 11         for finder, name, ispkg in pkgutil.iter_modules()
     12         if name.startswith(prefix)
     13     }

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py in <dictcomp>(.0)
     10         name: importlib.import_module(name)
     11         for finder, name, ispkg in pkgutil.iter_modules()
---> 12         if name.startswith(prefix)
     13     }
     14 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py in <module>
     89 # MAGIC telescope description
     90 OPTICS = OpticsDescription.from_name('MAGIC')
---> 91 MAGICCAM = CameraDescription.from_name("MAGICCam")
     92 pulse_shape_lo_gain = np.array([0., 1., 2., 1., 0.])
     93 pulse_shape_hi_gain = np.array([1., 2., 3., 2., 1.])

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/instrument/camera/description.py in from_name(cls, camera_name)
     71         geometry = CameraGeometry.from_name(camera_name)
     72         try:
---> 73             readout = CameraReadout.from_name(camera_name)
     74         except FileNotFoundError:
     75             readout = None

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/instrument/camera/readout.py in from_name(cls, camera_name, version)
    118             camera_name=camera_name, verstr=verstr
    119         )
--> 120         table = get_table_dataset(tabname, role="dl0.tel.svc.camera")
    121         return CameraReadout.from_table(table)
    122 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py in get_table_dataset(table_name, role, **kwargs)
    258     }
    259 
--> 260     return try_filetypes(table_name, role, table_types, **kwargs)
    261 
    262 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py in try_filetypes(basename, role, file_types, url, **kwargs)
    214             filename = basename + ext
    215             try:
--> 216                 path = get_dataset_path(filename, url=url)
    217                 break
    218             except (FileNotFoundError, HTTPError):

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py in get_dataset_path(filename, url)
    159     # last, try downloading the data
    160     try:
--> 161         return download_file_cached(filename, default_url=url, progress=True)
    162     except HTTPError as e:
    163         # let 404 raise the FileNotFoundError instead of HTTPError

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py in download_file_cached(name, cache_name, auth, env_prefix, default_url, progress)
    146     url = base_url + "/" + str(name).lstrip("/")
    147     return download_cached(
--> 148         url, cache_name=cache_name, auth=auth, env_prefix=env_prefix, progress=progress
    149     )

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py in download_cached(url, cache_name, auth, env_prefix, progress)
     84     lock_file = path.with_suffix(path.suffix + ".lock")
     85 
---> 86     with FileLock(lock_file):
     87         # if we already dowloaded the file, just use it
     88         if path.is_file():

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/filelock.py in __enter__(self)
     30                     )
     31                 bar.update(1)
---> 32                 time.sleep(0.1)
     33 
     34     def __exit__(self, exc_type, exc_value, traceback):

KeyboardInterrupt: 

In [5]: from ctapipe.io import HDF5TableWriter
                                                 ^C---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/filelock.py in __enter__(self)
     21             try:
---> 22                 self.path.open("x").close()
     23                 break

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/pathlib.py in open(self, mode, buffering, encoding, errors, newline)
   1207         return io.open(self, mode, buffering, encoding, errors, newline,
-> 1208                        opener=self._opener)
   1209 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/pathlib.py in _opener(self, name, flags, mode)
   1062         # A stub for the opener argument to built-in open()
-> 1063         return self._accessor.open(self, flags, mode)
   1064 

FileExistsError: [Errno 17] File exists: '/home/yoshiki.ohtani/.cache/ctapipe/cccta-dataserver.in2p3.fr/data/ctapipe-extra/v0.3.3/MAGICCam.camreadout.fits.gz.lock'

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-5-f0731f6ee983> in <module>
----> 1 from ctapipe.io import HDF5TableWriter

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/io/__init__.py in <module>
     15 
     16 # import IO plugins with their event sources
---> 17 detect_and_import_io_plugins()
     18 
     19 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py in detect_and_import_io_plugins()
     15 
     16 def detect_and_import_io_plugins():
---> 17     return detect_and_import_plugins(prefix="ctapipe_io_")

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py in detect_and_import_plugins(prefix)
      9     return {
     10         name: importlib.import_module(name)
---> 11         for finder, name, ispkg in pkgutil.iter_modules()
     12         if name.startswith(prefix)
     13     }

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py in <dictcomp>(.0)
     10         name: importlib.import_module(name)
     11         for finder, name, ispkg in pkgutil.iter_modules()
---> 12         if name.startswith(prefix)
     13     }
     14 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py in <module>
     89 # MAGIC telescope description
     90 OPTICS = OpticsDescription.from_name('MAGIC')
---> 91 MAGICCAM = CameraDescription.from_name("MAGICCam")
     92 pulse_shape_lo_gain = np.array([0., 1., 2., 1., 0.])
     93 pulse_shape_hi_gain = np.array([1., 2., 3., 2., 1.])

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/instrument/camera/description.py in from_name(cls, camera_name)
     71         geometry = CameraGeometry.from_name(camera_name)
     72         try:
---> 73             readout = CameraReadout.from_name(camera_name)
     74         except FileNotFoundError:
     75             readout = None

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/instrument/camera/readout.py in from_name(cls, camera_name, version)
    118             camera_name=camera_name, verstr=verstr
    119         )
--> 120         table = get_table_dataset(tabname, role="dl0.tel.svc.camera")
    121         return CameraReadout.from_table(table)
    122 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py in get_table_dataset(table_name, role, **kwargs)
    258     }
    259 
--> 260     return try_filetypes(table_name, role, table_types, **kwargs)
    261 
    262 

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py in try_filetypes(basename, role, file_types, url, **kwargs)
    214             filename = basename + ext
    215             try:
--> 216                 path = get_dataset_path(filename, url=url)
    217                 break
    218             except (FileNotFoundError, HTTPError):

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py in get_dataset_path(filename, url)
    159     # last, try downloading the data
    160     try:
--> 161         return download_file_cached(filename, default_url=url, progress=True)
    162     except HTTPError as e:
    163         # let 404 raise the FileNotFoundError instead of HTTPError

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py in download_file_cached(name, cache_name, auth, env_prefix, default_url, progress)
    146     url = base_url + "/" + str(name).lstrip("/")
    147     return download_cached(
--> 148         url, cache_name=cache_name, auth=auth, env_prefix=env_prefix, progress=progress
    149     )

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py in download_cached(url, cache_name, auth, env_prefix, progress)
     84     lock_file = path.with_suffix(path.suffix + ".lock")
     85 
---> 86     with FileLock(lock_file):
     87         # if we already dowloaded the file, just use it
     88         if path.is_file():

/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/filelock.py in __enter__(self)
     30                     )
     31                 bar.update(1)
---> 32                 time.sleep(0.1)
     33 
     34     def __exit__(self, exc_type, exc_value, traceback):

KeyboardInterrupt: 
```

Actually when importing the HDF5TableWriter at the first time, I see the following messages:

```
Downloading optics.ecsv.txt: 100%
Downloading MAGICCam.camgeom.fits.gz: 100%
```

Then I could run the Cal->DL1 process script without problems, but suddenly it didn't work and the message "Another process is already running, waiting:" is shown, which comes from ctapipe.utils.filelock.py that appeared since ctapipe v0.12.0. And since I see the error message `FileExistsError: [Errno 17] File exists: '/home/yoshiki.ohtani/.cache/ctapipe/cccta-dataserver.in2p3.fr/data/ctapipe-extra/v0.3.3/MAGICCam.camreadout.fits.gz.lock'`, I tried deleting all the caches and import HDF5TableWriter, and then I see again the messages about downloading the `optics.ecsv.txt` and `MAGICCam.camgeom.fits.gz` (and they are stored again in the cache directory), but the script now works fine. 

Do you think it is related to this issue? Actually I don't understand what happens... it would be great it you could give me some insights.

**Comment by YoshikiOhtani** [comment]
OK I faced the same problem, and it seems it happens when I submitted subrun-wise batch jobs, and I see the following error messages in the log file:

```
(magicctapipe) [yoshiki.ohtani@cp01 1.magic_cal_to_dl1]$ cat ~/Crab/2020_11_18/1.magic_cal_to_dl1/logs/M1_run05093174.001.job14073982.log 
Traceback (most recent call last):
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    % (self.host, self.timeout),
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x2b0a8760a350>, 'Connection to cccta-dataserver.in2p3.fr timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='cccta-dataserver.in2p3.fr', port=80): Max retries exceeded with url: /data/ctapipe-extra/v0.3.3/MAGICCam.camreadout.fits.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x2b0a8760a350>, 'Connection to cccta-dataserver.in2p3.fr timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoshiki.ohtani/combined_analysis/real/CrabNebula/2020_11_18/1.magic_cal_to_dl1/magic_data_cal_to_dl1.py", line 30, in <module>
    from ctapipe.io import HDF5TableWriter
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/io/__init__.py", line 17, in <module>
    detect_and_import_io_plugins()
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py", line 17, in detect_and_import_io_plugins
    return detect_and_import_plugins(prefix="ctapipe_io_")
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py", line 11, in detect_and_import_plugins
    for finder, name, ispkg in pkgutil.iter_modules()
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/core/plugins.py", line 12, in <dictcomp>
    if name.startswith(prefix)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py", line 91, in <module>
    MAGICCAM = CameraDescription.from_name("MAGICCam")
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/instrument/camera/description.py", line 73, in from_name
    readout = CameraReadout.from_name(camera_name)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/instrument/camera/readout.py", line 120, in from_name
    table = get_table_dataset(tabname, role="dl0.tel.svc.camera")
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py", line 260, in get_table_dataset
    return try_filetypes(table_name, role, table_types, **kwargs)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py", line 216, in try_filetypes
    path = get_dataset_path(filename, url=url)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/datasets.py", line 161, in get_dataset_path
    return download_file_cached(filename, default_url=url, progress=True)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py", line 148, in download_file_cached
    url, cache_name=cache_name, auth=auth, env_prefix=env_prefix, progress=progress
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py", line 104, in download_cached
    download_file(url=url, path=path, auth=auth, progress=progress)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/ctapipe/utils/download.py", line 33, in download_file
    with requests.get(url, stream=True, auth=auth, timeout=5) as r:
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magicctapipe/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='cccta-dataserver.in2p3.fr', port=80): Max retries exceeded with url: /data/ctapipe-extra/v0.3.3/MAGICCam.camreadout.fits.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x2b0a8760a350>, 'Connection to cccta-dataserver.in2p3.fr timed out. (connect timeout=5)'))
(magicctapipe) [yoshiki.ohtani@cp01 1.magic_cal_to_dl1]$ 
```

It was not happened until yesterday and so I think something must be changed around today. Do you have any thoughts about this?

**Comment by aleberti** [comment]
Mmmh today I had similar issues when trying to make tests pass, it seems that the CTA server sometimes fails in the connection, nothing we have control. Nothing changed in the master branches, they are basically the same as you tested in the last days. The refactoring is not an issue since it is happening in a separate branch. For magic-cta-pipe few commits were pushed but as you know they are related to packaging and the readme, so they don't interfere.

**Comment by YoshikiOhtani** [comment]
Hm I see, thanks, then I will try to do that tomorrow...

**Comment by YoshikiOhtani** [comment]
OK so it seems I finally solved this problem... in order to simplify the situation, I created an environment which is created by `ctapipe v0.12.0 environment.yml`, and tried importing the `HDF5TableWriter` in a terminal (cp01) and also in a batch job, and they don't show any issues. However, once I installed `ctapipe_io_magic v0.4.0` in the `ctapipe v0.12.0` environment, importing the `HDF5TableWriter` in a batch job shows the time out error. Then I noticed that importing any modules in `ctapipe.io` starts the initialization defined in `ctapipe/io/__init__.py` and it looks into the `ctapipe_io_magic/__init__.py`. Then there is a definition of the MAGIC camera description `MAGICCAM = CameraDescription.from_name('MAGICCam')`, and then as @aleberti  mentioned the `CameraDescription` tries to load the `MAGICCam.camreadout.fits.gz` file. I think it first look into the /`home/user/.cache/ctapipe` directory, but if it doesn't exist it tries to download from the CTA data server (cccta-dataserver.in2p3.fr), where the file still doesn't exist. Then I think when running the script in the terminal it somehow continues the process without any error messages, but in case of the batch job it shows a time out error, which was not happened last week but now it happens - one possibility is some settings of the IT Container batch job system changed recently. 

So I tried creating the `MAGICCam.camreadout.fits.gz` file by myself, and now the script works fine in both terminal and a batch job. So now it would be a bit urgent to upload the `MAGICCam.camreadout.fits.gz` file in the CTA data server. @aleberti, is it possible for you to upload the file? I think the one defined in ctapipe_io_magic would be ok for the moment.

**Comment by aleberti** [comment]
Ok, I can ask Max if he can do it, I don't know who is responsible of that CTA dataserver.

**Comment by YoshikiOhtani** [comment]
Thank you very much!

**Comment by aleberti** [comment]
As suggested by Max, I will do two things:
- ask to Johan to upload the MAGIC readout file
- add files needed for the CameraDescription into the repository itself

**Comment by aleberti** [comment]
Please @YoshikiOhtani try again using the master branch.

**Comment by YoshikiOhtani** [comment]
Thanks Alessio but I have a few comments on the master branch one, so I will create an issue page now.
