### ISSUE TITLE
Error: parsing data information from Calibrated-MAGIC files

### ISSUE THREAD

**Issue by aaguasca** [cta-observatory/ctapipe_io_magic#67]
An error pop-ups when processing some Calibrated-MAGIC files to DL1.

I used the ctapipe_io_magic version nested in magic-cta-pipe v0.3.0 and v0.3.1. For both versions, I got the same error. It is the following:

```
Traceback (most recent call last):
  File "/fefs/aswg/workspace/arnau.aguasca/miniconda3/envs/magic-lst1/bin/magic_calib_to_dl1", line 8, in <module>
    sys.exit(main())
  File "/fefs/aswg/workspace/arnau.aguasca/miniconda3/envs/magic-lst1/lib/python3.8/site-packages/magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py", line 387, in main
    magic_calib_to_dl1(args.input_file, args.output_dir, config, args.process_run)
  File "/fefs/aswg/workspace/arnau.aguasca/miniconda3/envs/magic-lst1/lib/python3.8/site-packages/magicctapipe/scripts/lst1_magic/magic_calib_to_dl1.py", line 97, in magic_calib_to_dl1
    event_source = MAGICEventSource(input_file, process_run=process_run)
  File "/fefs/aswg/workspace/arnau.aguasca/miniconda3/envs/magic-lst1/lib/python3.8/site-packages/ctapipe_io_magic/__init__.py", line 215, in __init__
    self.is_stereo, self.is_sumt = self.parse_data_info()
  File "/fefs/aswg/workspace/arnau.aguasca/miniconda3/envs/magic-lst1/lib/python3.8/site-packages/ctapipe_io_magic/__init__.py", line 549, in parse_data_info
    L3Table = L3Table_array[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by aleberti** [comment]
Hi Arnau, can you give me a list of such (sub)runs? I want to understand if there was a problem when the report information was merged into the files.

**Comment by aleberti** [comment]
I close this, but opened a discussion with instructions on how to proceed for similar cases: https://github.com/cta-observatory/ctapipe_io_magic/discussions/77
